#re-raising an error
try:
    raise NameError
except:
    print("Re-raising an error:::::")
    raise